"""
SQLite-based deduplication database for staging daemon.

Tracks processed files by path signature and content hash to avoid
re-processing files that haven't changed.
"""
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .config import DB_PATH


def init_db(db_path: Path = DB_PATH) -> sqlite3.Connection:
    """
    Create or open the SQLite database used to track processed files for deduplication.
    
    Ensures the parent directory for db_path exists, opens or creates the SQLite file, creates the `processed` table (columns: `sig`, `src_path`, `size`, `mtime_ns`, `first_seen`, `last_seen`, `dest_path`, `classification`, `profile`, `content_sig`) and a partial index on `content_sig` for content-based deduplication, then commits the schema changes.
    
    Parameters:
        db_path (Path): Filesystem path to the SQLite database file.
    
    Returns:
        sqlite3.Connection: Open connection to the initialized SQLite database.
    """
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.Connection(str(db_path))
    
    conn.execute("""
        CREATE TABLE IF NOT EXISTS processed (
            sig TEXT PRIMARY KEY,
            src_path TEXT NOT NULL,
            size INTEGER NOT NULL,
            mtime_ns INTEGER NOT NULL,
            first_seen TEXT NOT NULL,
            last_seen TEXT NOT NULL,
            dest_path TEXT NOT NULL,
            classification TEXT,
            profile TEXT,
            content_sig TEXT
        )
    """)
    
    # Index on content signature for content-based dedup
    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_content_sig
        ON processed(content_sig)
        WHERE content_sig IS NOT NULL
    """)
    
    conn.commit()
    return conn


def path_signature(p: Path) -> str:
    """
    Create a signature for a file using its resolved path, size, and modification time.
    
    Parameters:
        p (Path): File path to generate the signature for.
    
    Returns:
        str: Signature in the format "<resolved_path>:<size>:<mtime_ns>" where <resolved_path> is the path resolved to an absolute canonical form, <size> is the file size in bytes, and <mtime_ns> is the modification time in nanoseconds.
    """
    stat = p.stat()
    return f"{p.resolve()}:{stat.st_size}:{stat.st_mtime_ns}"


def already_processed(conn: sqlite3.Connection, sig: str) -> bool:
    """
    Determine whether a path signature is present in the processed database.
    
    Parameters:
        sig (str): Path signature generated by path_signature() that identifies a file.
    
    Returns:
        `true` if a row with the given signature exists in the processed table, `false` otherwise.
    """
    cursor = conn.execute(
        "SELECT 1 FROM processed WHERE sig = ?",
        (sig,)
    )
    return cursor.fetchone() is not None


def already_processed_by_content(
    conn: sqlite3.Connection,
    content_sig: Optional[str],
) -> bool:
    """
    Determine whether a file with the given content signature has already been recorded.
    
    If `content_sig` is None or empty, the function returns `false` without querying the database.
    
    Parameters:
        content_sig (Optional[str]): Content signature (for example, a SHA256 of head+tail) used for content-based deduplication.
    
    Returns:
        `true` if a matching content signature exists in the processed table, `false` otherwise.
    """
    if not content_sig:
        return False
    
    cursor = conn.execute(
        "SELECT 1 FROM processed WHERE content_sig = ?",
        (content_sig,)
    )
    return cursor.fetchone() is not None


def record_processed(
    conn: sqlite3.Connection,
    sig: str,
    src_path: Path,
    dest_path: Path,
    classification: str,
    profile: str,
    content_sig: Optional[str] = None,
) -> None:
    """
    Record that a source file was processed by inserting or updating its entry in the deduplication database.
    
    Parameters:
        conn (sqlite3.Connection): Open SQLite connection to the deduplication database.
        sig (str): Path-based signature for the source file (unique key).
        src_path (Path): Original source file path.
        dest_path (Path): Destination path where the file was staged.
        classification (str): Classification label assigned to the file.
        profile (str): Staging profile used (for example, "full" or "light").
        content_sig (Optional[str]): Optional content-based signature (hash) for content deduplication.
    
    Behavior:
        Inserts a new row with file metadata (size, mtime, first_seen, last_seen, etc.) or updates the existing row with the same `sig`, refreshing stored metadata and `last_seen`. Commits the transaction.
    """
    stat = src_path.stat()
    now = datetime.now(timezone.utc).isoformat()
    
    conn.execute("""
        INSERT INTO processed (
            sig, src_path, size, mtime_ns,
            first_seen, last_seen,
            dest_path, classification, profile, content_sig
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(sig) DO UPDATE SET
            src_path = excluded.src_path,
            size = excluded.size,
            mtime_ns = excluded.mtime_ns,
            last_seen = excluded.last_seen,
            dest_path = excluded.dest_path,
            classification = excluded.classification,
            profile = excluded.profile,
            content_sig = excluded.content_sig
    """, (
        sig,
        str(src_path),
        stat.st_size,
        stat.st_mtime_ns,
        now,
        now,
        str(dest_path),
        classification,
        profile,
        content_sig,
    ))
    conn.commit()