# Copy to /etc/wade/workers.yaml and tweak
global:
  max_workers: 1               # keep simple; can raise later
  fail_fast: false
  write_placeholders: true
  default_date_format: "%Y-%m-%dT%H%M%S"

volatility:
  enabled: true
  vol_bin: "${VOL_BIN}"
  default_profile: auto
  # Modules by OS family; feel free to expand
  modules:
    windows:
      - windows.pslist
      - windows.pstree
      - windows.netscan
      - windows.cmdline
      - windows.services
    linux:
      - linux.pslist
      - linux.lsof
      - linux.mount
    mac:
      - mac.pslist
  extra_args: ["--output", "json"]   # adjust to your vol3 renderer
  timeout_sec: 1800

dissect:
  enabled: true
  # How to get EVTX out; simplest is mount+copy
  mount_cmd: ["target-mount", "--read-only", "{image}", "{mountpoint}"]
  umount_cmd: ["fusermount", "-u", "{mountpoint}"]
  evtx_globs:
    - "Windows/System32/winevt/Logs/*.evtx"
    - "Windows/system32/winevt/Logs/*.evtx"   # case alt
  copy_limit_mb: 20480

hayabusa:
  enabled: true
  bin: "${HAYABUSA_BIN}"
  args: ["detect", "-d", "{evtx_dir}", "--format", "jsonl", "-o", "{outfile}"]
  timeout_sec: 3600
  module_name: "hayabusa.detect"     # for folder naming & injected 'module'

bulk_extractor:
  enabled: true
  bin: "${BULKEX_BIN}"
  args: ["-o", "{outdir}", "{image}"]
  parse_outputs: true
  parse_kinds: ["email", "url", "ccn"]  # which bulk_extractor *.txt to JSONL

autopsy:
  enabled: true
  # Writes a tiny XML manifest next to each disk image
  template:
    case_name: "{hostname}_{date}"
    data_source_path: "{image}"
    time_zone: "UTC"
    notes: "Autogen by WADE workers"

dedupe:
  # Use both: quick local status + (optional) Splunk REST search
  use_local_status: true
  use_splunk_rest: false
  local_key: "{tool}:{module}:{hostname}:{input_hash}"
  splunk:
    url: "${SPLUNK_URL}"
    user: "${SPLUNK_USER}"
    pass: "${SPLUNK_PASS}"
    token: "${SPLUNK_TOKEN}"
    index_hint: "wade_*"
